blacklistedOres = []
enableNoJeiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = true
enableAe2Integration = true
generateOres = true
datagenOnStartup = true
loadRuntimeGeneratedResources = true
